name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install frontend deps
        run: npm ci
      - name: Typecheck and build frontend
        run: npm run build
      - name: Install server deps
        run: |
          cd server
          npm ci
      - name: Lint placeholder (extend later)
        run: echo "lint todo"

